### ISSUE TITLE
libvte for python is depreciated

### ISSUE THREAD

**Issue by Ravinou** [mjun/gnome-connection-manager#14]
Hi, and thank you so much for your work :)
I use gnome connection manager since many years and i just upgrade my Ubuntu to 19.04 (from 18.10) and GCM didn't work anymore :'(

I have the error : "You must install libvte for python" but ... : https://bugs.launchpad.net/ubuntu/+source/vte/+bug/1820143

The package is missing and has been removed.

Thanks.

**Comment by dssouza-ti** [comment]
Hello.

I use Ubuntu 18.04, but while testing 19.04 I had the same issue. I'm not a developer, but with a little research I found some information stating that softwares need to be ported from gtk2 to gtk3 using a different version of vte libraries.

More specifically, I have found this statement: "Instead of using gtk2 and python-vte, apps should switch to using GObject Introspection and gtk3 using the gir1.2-vte-2.91 package provided by the vte2.91 source package." in this forum: https://ubuntuforums.org/showthread.php?t=2413202

Do you still work on this project and have plans to actually work on this port? If so, do you need any donations to help the development costs? As Ravinou, I use this software for many years and I just love it. I really would like to see it working in gtk3 environments.

Thanks and regards,
Diego Souza

**Comment by mitquinn** [comment]
I would be interested in using it as well. I wouldn't mind donating to an update pool. Does it just make more sense at this point to fork the project and update it ourselves since this doesn't seem to be maintained anymore?

**Comment by dssouza-ti** [comment]
Hi mitquinn,

I emailed this repository maintainer asking if he had plans to keep working in this project and he answered me, saying that he wants to do this update, but currently have no time due to his daily job and personal responsibilities. He also said that when he has the time, he will update this repository with information on the work and donations. Since I'm not planning on updating my Ubuntu until the next LTS release (20.04), I'll just wait for news on this project. As I said before, I'm not a developer, so I wouldn't be able to help if you decided to fork this project and do the update yourself anyway.

Regards,
Diego Souza

**Comment by shaphiro** [comment]
+1

**Comment by daradermody** [comment]
+1

**Comment by daradermody** [comment]
A workaround is to manually install the lib and its dependencies (see [here](https://github.com/daradermody/gnome-connection-manager#installing-on-ubuntu-1904)). I tried it and it works well.

**Comment by urkl** [comment]
+1
